## OPTIONS ##########################################################################################################
options:

  log:
    level: INFO

  INSTRUMENTS:
    SMC_CORVUS_XYZ:  # XYZ STAGE
      port: COM9
      baud_rate: 57600
      timeout: 0.5 # s
      unit: MICROMETER
      velocity: 800.0 # unit/s
      acceleration: 1000.0 # unit/s^2

#######################################################################################################################
